services:
  # OCR Backend API Service
  - type: web
    name: ocr-backend-service
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      cd ocr-backend
      pip install -r requirements.txt
    startCommand: |
      cd ocr-backend
      gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false  # This will be set manually in the Render dashboard